# Default config

UPW_DIR: '.upw/'

# Constants parameters (do not change)

hash:
  name: 'sha256'
  salt: 'upw'
  dklen: 100000

passwords_length: 16
spec_char_list:
  - '#'
  - '%'
  - '$'
  - '^'
  - '@'
  - '?'
  - '!'
  - '&'
  - '*'

emojish_list: 'ğŸ˜‚ğŸ˜„ğŸ˜ƒğŸ˜ŠğŸ˜‰ğŸ˜‡ğŸ¥°ğŸ˜ğŸ¤©ğŸ˜˜ğŸ˜—ğŸ˜šğŸ˜™ğŸ¥²ğŸ˜‹ğŸ˜›ğŸ˜œğŸ¤ªğŸ˜ğŸ¤—ğŸ¤­ğŸ¤«ğŸ¤”ğŸ¤ğŸ¤¨ğŸ˜ğŸ˜‘ğŸ˜¶ğŸ˜ğŸ˜ŒğŸ¤¤ğŸ˜´ğŸ¥ºğŸ˜³ğŸ˜¯ğŸ˜®ğŸ˜ğŸ¤“ğŸ¥¸ğŸ¥³ğŸ¤ ğŸ¥´ğŸ˜ˆâ¤ï¸ğŸ¤ŒğŸ¤šğŸ–ï¸âœ‹ğŸ––ğŸ‘‹âœŒï¸ğŸ¤™ğŸ‘‡ğŸ‘ˆğŸ¤ğŸ‘ŒğŸ¤˜ğŸ‘†ğŸ¤ŸğŸ‘¨â€ğŸ­ğŸ§‘â€ğŸ”¬ğŸ‘©ğŸ¼â€ğŸ’¼ğŸ§‘ğŸ¼â€ğŸ’»ğŸ§‘â€ğŸ’»ğŸ§‘â€ğŸ³ğŸ‘©â€ğŸ”¬ğŸ™‹â€â™€ï¸ğŸ§â€â™‚ï¸ğŸ™‹ğŸ¼ğŸ‘¨ğŸ¼â€âš•ï¸ğŸ¤·ğŸ¼â€â™€ï¸ğŸ‘¨â€ğŸ“ğŸ•µï¸â€â™‚ï¸ğŸ’‚ğŸ‘·ğŸ¤´ğŸ‘·â€â™€ï¸ğŸ¤µğŸ¤µğŸ¼â€â™€ï¸ğŸ§•ğŸ…'
